apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ibmoffices-app
  namespace: ibmoffices
spec:
  params:
    - default: 'https://github.com/Nordic-MVP-GitOps-Repos/ibm-offices'
      name: git-repo-url
      type: string
    - default: src/main/docker/Dockerfile.jvm
      name: dockerfile-path
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a538c423e7a11aae6ae582a411fdb090936458075f99af4ce5add038bb6983e8
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone-1-8-0
      workspaces:
        - name: output
          workspace: workspace
    - name: gradle
      params:
        - name: GRADLE_IMAGE
          value: 'docker.io/library/gradle:jdk11'
        - name: PROJECT_DIR
          value: .
        - name: TASKS
          value:
            - build
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: gradle
      workspaces:
        - name: source
          workspace: workspace
    - name: buildah
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/ibmoffices/ibmoffices:$(tasks.git-clone.results.commit)'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - gradle
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: apic-client
      params: 
        - name: APIC_CLIENT_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/ibmoffices/apic-client@sha256:df2af5ba8b5c0ddaf0586ba37c5465176f7b4fe6e279a84915a1a6b93ac26cc5

        - name: SCRIPT
          value: >
          
            export USERNAME=$(cat $(workspaces.basic-auth.path)/username)
            
            export PASSWORD=$(cat $(workspaces.basic-auth.path)/password)
            
            export SERVER='https://api-connec-e1355ae2-platform-api-cp4i.itzroks-2700015rqr-7vz6mp-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-de.containers.appdomain.cloud/'
             
            export ORG='providerorg' 
            
            apic client-creds:clear
            
            apic client-creds:set /workspace/client-credentials/client-creds.json
            
            apic login -s $SERVER --username $USERNAME --password $PASSWORD --realm provider/default-idp-2
            
            set -x            
         
            curl -k https://secure-route-ibmoffices.itzroks-2700015rqr-7vz6mp-6ccd7f378ae819553d37d5f2ee142bd6-0000.eu-de.containers.appdomain.cloud/q/openapi > openapi.yaml
        
            cat openapi.yaml | yq '.info.title'
            
            apic me:get -s $SERVER
            
            #apic apis:list-all -s $SERVER --org $ORG --catalog sandbox --scope catalog
            
            apic draft-apis:create -o providerorg -s $SERVER openapi.yaml
      
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: apic-client
      workspaces:
        - name: workspace
          workspace: workspace
        - name: client-credentials
          workspace: client-credentials
        - name: basic-auth
          workspace: basic-auth
  workspaces:
    - name: workspace
    - name: client-credentials
    - name: basic-auth
